### ISSUE TITLE
Add credits to the repository owner and copyright footer below.

### ISSUE THREAD

**Issue by rajatrajputdev** [bhanusingh008/flappy-bird#10] opened 2024-10-01 03:39 UTC
A footer will look good and will let other users know about the repository. Kindly mark it under hacktoberfest.

**Comment by bhanu-io** [comment] 2024-10-01 04:03
I have marked it as "hacktoberfest" in the topic section in about. Do i have to mark it anywhere else too? Also check on your hacktober profile, it must be saying "waiting..."  alongside PR, smthing like that. If yes you're good to go

**Comment by rajatrajputdev** [comment] 2024-10-01 05:57
Actually, you have to manually label issues as hacktoberfest to bring them under hacktoberfest.

**Comment by bhanu-io** [comment] 2024-10-01 07:06
RIght, the issue is labelled now

**Closed as completed** 2024-10-03 03:21 UTC
Labels: hacktoberfest
